In [1]:
!pip install numpy

In [2]:
import numpy as np

What is NumPy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. It is the foundation of most scientific computing and data analysis in Python.

Key Features:

N-dimensional arrays: NumPy provides an efficient array structure (ndarray) for storing and manipulating dense data buffers in a contiguous block of memory.


Vectorized operations: NumPy allows for element-wise operations on entire arrays at once, making it efficient for large-scale numerical computations.


Broadcasting: NumPy enables flexible array manipulation by allowing arrays of different shapes and sizes to be combined using broadcasting rules.


Mathematical functions: NumPy includes a wide range of mathematical functions, such as trigonometric, exponential, and statistical operations, which can be applied to arrays element-wise.


Integration with other libraries: NumPy is widely used in conjunction with other popular scientific computing libraries in Python, such as SciPy, Pandas, and Scikit-learn.


Use Cases:
Scientific computing: NumPy is ideal for numerical simulations, data analysis, and visualization in fields like physics, engineering, and biology.


Data analysis: NumPy is used for data manipulation, filtering, and aggregation in data science and machine learning applications.


Machine learning: NumPy is a fundamental library for many machine learning algorithms and frameworks, such as TensorFlow and PyTorch.

In [3]:
List=[1,2,3,4]
print(List)

[1, 2, 3, 4]


In [4]:
#for numpy array creation

# 1 D array creation
lst_1d=np.array([1,2,3,4,5])
print("1 D array creation=",lst_1d)

# 2 D array creation
lst_2d=np.array([[1.1,2.2,3,],
                 [1,2,3]])
print("2 D array creation=",lst_2d)

# 3 D array creation
lst_3d=np.array([[[1,2,3],
                  [1,2,3],
                  [1,2,3]]])
print("3 D array creation=",lst_3d)

1 D array creation= [1 2 3 4 5]
2 D array creation= [[1.1 2.2 3. ]
 [1.  2.  3. ]]
3 D array creation= [[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [5]:
type(lst_1d)
type(lst_2d)
type(lst_3d)

numpy.ndarray

In [6]:
print(lst_1d.size)
print(lst_2d.size)
print(lst_3d.size)


5
6
9


In [7]:
print(lst_1d.shape)
print(lst_2d.shape)
print(lst_3d.shape)


(5,)
(2, 3)
(1, 3, 3)


In [8]:
print(lst_1d.dtype)
print(lst_2d.dtype)
print(lst_3d.dtype)


int32
float64
int32


In [9]:
lst_2d.transpose()

array([[1.1, 1. ],
       [2.2, 2. ],
       [3. , 3. ]])

In [10]:
print(lst_3d.transpose().shape)

(3, 3, 1)


In [11]:
#part 2
# np.empty((rows,cols),dtype)
np.empty((3,2),dtype=int)

array([[1653786560,        520],
       [         0,          0],
       [    131074, 1948393516]])

In [12]:
x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [13]:
x=np.zeros(5,int)
x

array([0, 0, 0, 0, 0])

In [14]:
x=np.ones((3,2),dtype=int)
x

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
# For string also
x=np.zeros((3,2),str)
print("x=>",x)
y=np.ones((3,2),str)
print("y=>",y)

x=> [['' '']
 ['' '']
 ['' '']]
y=> [['1' '1']
 ['1' '1']
 ['1' '1']]


In [16]:
#for bool function also
x=np.ones((2,3),bool)
y=np.zeros((2,3),bool)
print(x)
print(y)

[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]


In [17]:
#part 3
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [18]:
a=np.arange(2,10,2)
print(a)

[2 4 6 8]


In [19]:
#Reshape
a.reshape((2,2))
print(a)

[2 4 6 8]


In [20]:
b=np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
b.reshape((10,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [22]:
b.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])


a.ravel(): (i) Return only reference/view of original array (ii) If you modify the array you would notice that the value of original array also changes. (iii) Ravel is faster than flatten() as it does not occupy any memory. (iv) Ravel is a library-level function.

a.flatten() : (i) Return copy of original array (ii) If you modify any value of this array value of original array is not affected. (iii) Flatten() is comparatively slower than ravel() as it occupies memory. (iv) Flatten is a method of an ndarray object.

In [23]:
a.ravel()

array([2, 4, 6, 8])

In [27]:
a=np.arange(1,51)
print(a)
a=a.reshape(10,5)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [28]:
a[0]

array([1, 2, 3, 4, 5])

In [29]:
a[0,0]

1

In [30]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [31]:
a[1:4,0:3]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [32]:
a[:,2:5].dtype

dtype('int32')

In [38]:
a=np.arange(0,18).reshape(6,3)
b=np.arange(20,38).reshape(6,3)


In [39]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [40]:
print(b)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [41]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [42]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [43]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [44]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [45]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [46]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [47]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [48]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [50]:
print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [52]:
b=b.reshape(3,6)
b

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37]])

In [53]:
print(a.shape)
print(b.shape)

(6, 3)
(3, 6)


In [55]:
a@b   #cross multiplication using @ symbol

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [56]:
a.dot(b)  #cross multiplication using dot function

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [57]:
b.dot(a)

array([[1065, 1200, 1335],
       [1335, 1506, 1677],
       [1605, 1812, 2019]])

In [58]:
b.max()

37

In [59]:
b.min()

20

In [61]:
b.argmax()   
#The numpy function argmax returns the index of the maximum value in 
# the flattened array when called without specifying an axis.

17

In [62]:
np.sum(b)

513

In [63]:
np.sum(b,axis=0)

array([78, 81, 84, 87, 90, 93])

In [64]:
np.sum(b,axis=1)

array([135, 171, 207])

In [65]:
np.mean(b)

28.5

In [72]:
np.std(b,axis=1)

array([1.70782513, 1.70782513, 1.70782513])

In [73]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])

In [74]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [75]:
np.std(np.sum(b,axis=0))

5.123475382979799